version: "3"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://localhost:27017/shopping-cart
      - JWT_SECRET=your_jwt_secret
      - TOKE_EXPIRATION=1h
      - PORT=3000
    depends_on:
      - db

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
