version: "3"
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  backend:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongodb:27017/shopping-cart
      - JWT_SECRET=your_jwt_secret
      - TOKE_EXPIRATION=1h
      - PORT=3000
    depends_on:
      - mongodb
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
